### ISSUE TITLE
Add nuclear moderation commands

### ISSUE THREAD

**Issue by LivestC** [FlaringPhoenix/PteroManager#9]
I mean we need auto-moderation and moderation commands such as ban, kick, mute, blind, temporary, others ... In order not to use a typical bot with the typical reason 'everyone uses them', how to believe that mee6 or dyno is good but  it never was, it's just stable. lol.

**Comment by FlaringPhoenix** [comment]
We can just make a separate moderation bot.

**Comment by wolfier74** [comment]
> We can just make a separate moderation bot.

OK
